# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


def primevideo_search(driver, movie):
    driver.get("https://www.primevideo.com/")
    driver.find_element(By.ID, "pv-search-nav").send_keys(movie)
    driver.find_element(By.ID, "pv-search-nav").send_keys(Keys.ENTER)
    element = driver.find_element(By.CSS_SELECTOR, ".av-hover-wrapper:nth-child(1) img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    driver.find_element(By.CSS_SELECTOR, ".\\_1UBEhe .\\_1n8-io").click()
    driver.find_element(By.CSS_SELECTOR, ".fullscreenButton > .svgBackground").click()

def netflix_search(driver, movie, NETFLIX_USERNAME, NETFLIX_PASSWORD):
    driver.get("https://www.netflix.com/it-en/Login")
    # username = WebDriverWait(driver, 5).until(
    #     EC.visibility_of_element_located((By.XPATH, "//*[@id='id_userLoginId']"))
    # )
    # password = driver.find_element_by_xpath("//*[@id='id_password']")
    # username.send_keys(NETFLIX_USERNAME)
    # password.send_keys(NETFLIX_PASSWORD)
    # driver.find_element_by_xpath("//*[@id='appMountPoint']/div/div[3]/div/div/div[1]/form/button").click()
    profile = driver.find_elements_by_xpath(
        "//*[@id='appMountPoint']/div/div/div[1]/div[1]/div[""2]/div/div/ul/li[5]/div/a/div/div")
    profile[0].click() if len(profile) > 0 else 0
    time.sleep(1)
    driver.get(f"https://www.netflix.com/search?q={movie}")
    WebDriverWait(driver, 2).until(
        EC.visibility_of_element_located((By.XPATH, "//*[@id='title-card-0-0']/div[1]/a/div[1]/img"))
    ).click()
    WebDriverWait(driver, 2).until(
        EC.visibility_of_element_located((By.XPATH, "//*[@id='pane-Overview']/div/div/div/div[2]"))
    ).click()


def youtube_search(driver, video):
    driver.get("https://www.youtube.com/")
    driver.find_element(By.NAME, "search_query").send_keys(video)
    driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
    element = driver.find_element(By.CSS_SELECTOR, ".ytd-item-section-renderer:nth-child(1) > #dismissable #img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    driver.find_element(By.CSS_SELECTOR, ".style-scope:nth-child(2) > #label-container").click()
